#
# /usr/share/doc/rhel-system-roles/network/example-bridge_with_vlan-playbook.yml 
- name: Install RPM package
  dnf:
    name: rhel-system-roles
    state: present

- name: find the network interface name
  set_fact:
    ethernet_port: "{{ ansible_facts['default_ipv4']['interface'] }}"

- name: display the name
  debug:
    var: ethernet_port

# use gather_facts to set ansible_python
- name: use rhel-system-role network
  vars:
    network_connections:
      #
      # Create a bridge profile
      - name: pubbr0
        state: up
        type: bridge
        #interface_name: pubbr0 # defaults to the connection name
        ip:
          dhcp4: yes
          auto6: yes
      #
      # set an ethernet port to the bridge
      - name: "pubbr0-{{ ethernet_port }}"
        state: up
        type: ethernet
        interface_name: "{{ ethernet_port }}"
        controller: pubbr0
        #controller: public-bridge
        port_type: bridge
  include_role:
    name: rhel-system-roles.network

# https://docs.ansible.com/ansible/latest/collections/community/libvirt/virt_net_module.html
#

- name: install RPM packages
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - python3-libvirt
    - python3-lxml

# Define a new network
- community.libvirt.virt_net:
    command: define
    name: public0
    xml: '{{ lookup("file", "net-pubbr0.xml") }}'

# Start a network
- community.libvirt.virt_net:
    command: create
    name: public0

# Ensure that a network is active (needs to be defined and built first)
- community.libvirt.virt_net:
    state: active
    name: public0

# Ensure that a given network will be started at boot
- community.libvirt.virt_net:
    autostart: yes
    name: public0

